version: '3.8'

services:
  strapi:
    build:
      context: ./apps/strapi
      dockerfile: Dockerfile
    container_name: orgma-strapi
    ports:
      - "1337:1337"
    environment:
      - NODE_ENV=production
    env_file:
      - ./apps/strapi/.env
    volumes:
      - ./apps/strapi/config:/app/config
      - ./apps/strapi/src:/app/src
      - ./apps/strapi/public:/app/public
      - strapi-data:/app/.tmp
    networks:
      - orgma-network


  # Если нужно, добавьте MinIO/S3
  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: orgma-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
      - ./cors.json:/etc/minio/cors.json
    networks:
      - orgma-network

volumes:
  strapi-data:
  minio-data:

networks:
  orgma-network:
    driver: bridge