import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en" suppressHydrationWarning>
      <Head/>
      <body>
      <Sidebar/>
      <div className="main-container">
        <Header
            title={"Системы дистанционного образования"}
            description={
              <div className={styles.header__desc_p}>
                Для входа во все системы используется <b>Единый идентификатор ВУЗа. Как получить идентификатор? </b><br/>
                <br/>Если у вас возникли проблемы с доступом, обращайтесь по email:<b>623@orgmu.ru</b><br/>
              </div>
            }
        />
        {children}
        <Footer/>
      </div>
      </body>
      </html>
  );
}
