import type { Metadata } from "next";

import { Header, HeaderRight, Footer, Head } from "@repo/ui";
import Script from 'next/script'
import "./globals.css";
import React from "react";
import { getFooterData } from '../lib/strapi';
import {Grid} from "@mui/material";
import Container from "@mui/material/Container"; // Импортируйте функцию

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
    const footerData = await getFooterData();
  return (
      <html lang="en" suppressHydrationWarning>
      <Head/>
      <body>
      {/*<Sidebar/>*/}
      <div className="main-container">

          <Container maxWidth="xl" sx={{marginBottom: 4, marginTop: { xs: 3, md: 5, lg: 10 }}}>
              <header className="flex text-[var(--text-color)] p-[15px] mb-[30px]">
                  <Grid container>
                      <Grid size={{xs: 12, md: 6, lg: 6, xl: 7}}>
                          <Header/>
                      </Grid>
                      <Grid size={{xs: 12, md: 6, lg: 6, xl: 5}}>
                          <HeaderRight
                              title={"УПРАВЛЕНИЕ ПО ЦИФРОВОМУ РАЗВИТИЮ"}
                              description={"Руководитель подразделения: Кирьяков Дмитрий Анатольеви 460014, Оренбургская область, " +
                                  "город Оренбург, ул. Советская, 6Телефон: +7 (3532) 50-06-06 доб.623.Электронная почта: d.a.kir@orgma.ru"
                              }
                          />
                      </Grid>
                  </Grid>
              </header>
          </Container>


          {children}

          <Footer footerData={footerData} />

      </div>
      <Script src="WidgetMiBase.js"></Script>
      </body>
      </html>
  );
}
