import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en" suppressHydrationWarning>
      <Head/>
      <body>
      <Sidebar/>
      <div className="main-container">
        <Header
            title={"Оплата услуг"}
            description={
              <div className={styles.header__desc_p}>
                  Оплата услуг
              </div>
            }
        />
        {children}
        <Footer/>
      </div>
      </body>
      </html>
  );
}
